name: cep_flutter_web
description: Flutter Web app for CEP backend
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  google_sign_in: ^6.2.1
  http: ^0.13.6
  intl: ^0.18.1
  image_picker: ^1.0.4
  universal_io: ^2.2.2
  pdf: ^3.10.8
  printing: ^5.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/Roboto.ttf
